networks:
  api-net:
    driver: bridge

services:
  postgres:
    container_name: db-test
    image: pgvector/pgvector:pg17
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=wazzy_test
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=2621kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "statement_timeout=30000"
      - "-c"
      - "idle_in_transaction_session_timeout=60000"
      - "-c"
      - "tcp_keepalives_idle=60"
      - "-c"
      - "tcp_keepalives_interval=10"
      - "-c"
      - "tcp_keepalives_count=6"
    tmpfs:
      - /var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - api-net

  redis:
    container_name: redis-test
    image: redis:7-alpine
    ports:
      - "6380:6379"
    restart: unless-stopped
    command: redis-server --appendonly no
    tmpfs:
      - /data
    networks:
      - api-net
