services:
  app:
    build:
      # context: .
      # target: runner
      # dockerfile: Dockerfile
      image: jhonathangalhardo/calendar:latest
    container_name: app
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/calendar
      - SECRET_KEY=supersecret123
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate dev --create-only --name calendar && npx prisma migrate deploy && npm start"

  postgres:
    container_name: db
    image: pgvector/pgvector:pg17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=calendar
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/calendar?sslmode=disable # REMOVE SSL DISABLE
    ports:
      - '8081:8081'
    depends_on:
      - postgres
