services:
  nextjs-app:
    build: .
    ports:
      - '3001:3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`http://teste22_calendar:3000`)"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    restart: always
