services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/calendar
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    # command: sh -c "npx prisma migrate deploy && node server.js"
    command: 
      sh -c "
        echo 'Waiting for Postgres...';
        until pg_isready -h postgres -U myuser; do
          sleep 2;
        done;
        npx prisma migrate dev --name init;
        echo 'Applying migrations...';
        npx prisma migrate deploy;
        echo 'Starting app...';
        node server.js
      "

  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=calendar
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/calendar?sslmode=disable # REMOVE SSL DISABLE
    ports:
      - '8081:8081'
    depends_on:
      - postgres
