services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgres://postgres:Y7q%40kR3p!zW1Lx9u@postgres:5432/calendar
    restart: always

  postgres:
    image: pgvector/pgvector:pg17 
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Y7q%40kR3p!zW1Lx9u
      - POSTGRES_DB=calendar
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
