services:
  nextjs-app:
    build: .
    ports:
      - '3001:3000'
    restart: always

  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sua_senha_segura
      - POSTGRES_DB=nomedobanco
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
