services:
  app:
    build: .
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/calendar?schema=public
    restart: always

  postgres:
    image: pgvector/pgvector:pg17 
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=calendar
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
