import type { Metadata } from 'next';
import './globals.css';
import { UserProvider } from '@/contexts/user';
import { ReactQueryProvider } from '@/components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased !overflow-x-hidden flex"
        suppressHydrationWarning
      >
        <ReactQueryProvider enablePersistence={false} enableCrossTabSync={true}>
          <UserProvider>{children}</UserProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
